spring.application.name=api_gateway
server.port=8080

spring.cloud.gateway.routes[0].id=asisteuco_id
spring.cloud.gateway.routes[0].uri=http://localhost:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/**

spring.cloud.gateway.routes[1].id=oauth_login
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/login/oauth/**


spring.security.oauth2.client.registration.github.client-id=${GITHUBID}
spring.security.oauth2.client.registration.github.client-secret=${SECRETGITHUB}

spring.security.oauth2.client.registration.google.client-id=${GOOGLEID}
spring.security.oauth2.client.registration.google.client-secret=${SECRETGOOGLE}
spring.security.oauth2.client.registration.google.scope=openid,email,profile

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-btjk5wnke0v6z6tj.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audiences=https://asisteuco.api


