spring.application.name=api_gateway
server.port=8080

# 1. Ruta para asistencias
spring.cloud.gateway.routes[0].id=asistencias
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/asisteuco/apigateway/asistencias
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/asisteuco/apigateway/asistencias, /api/v1/asistencias

# 2. Ruta para login/oauth (ruta específica SIN /api/v1)
spring.cloud.gateway.routes[1].id=oauth_login
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/asisteuco/apigateway/login/oauth
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/asisteuco/apigateway/login/oauth, /login/oauth

# 3. Ruta general para utilidades-ms (cualquier otro endpoint con /api/v1)
spring.cloud.gateway.routes[2].id=utilidades
spring.cloud.gateway.routes[2].uri=http://localhost:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/asisteuco/apigateway/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/asisteuco/apigateway/(?<segment>.*), /api/v1/${segment}






spring.security.oauth2.client.registration.github.client-id=${GITHUBID}
spring.security.oauth2.client.registration.github.client-secret=${SECRETGITHUB}

spring.security.oauth2.client.registration.google.client-id=${GOOGLEID}
spring.security.oauth2.client.registration.google.client-secret=${SECRETGOOGLE}
spring.security.oauth2.client.registration.google.scope=openid,email,profile

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-btjk5wnke0v6z6tj.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audiences=https://asisteuco.api


