spring.application.name=utilidades-ms
server.port=8082
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.context.annotation.ClassPathBeanDefinitionScanner=DEBUG
spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=https://keyvaulenterprise.vault.azure.net/
azure.keyvault.url=https://keyvaulenterprise.vault.azure.net/

spring.cloud.azure.credential.client-id=${AZURE_CLIENT_ID}
spring.cloud.azure.credential.client-secret=${AZURE_CLIENT_SECRET}
spring.cloud.azure.profile.tenant-id=${AZURE_TENANT_ID}

spring.datasource.url=${DBURL}
spring.datasource.username=${DBUSERNAME}
spring.datasource.password=${DBPASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true